//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mailer.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mailer.Resources.Localization.MainResources", typeof(MainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We are sorry but something goes wrong. We will try to fix this as soon as possible..
        /// </summary>
        public static string CommonErrorViewContent {
            get {
                return ResourceManager.GetString("CommonErrorViewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart.
        /// </summary>
        public static string CommonErrorViewRestart {
            get {
                return ResourceManager.GetString("CommonErrorViewRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Oh... something happened :(.
        /// </summary>
        public static string CommonErrorViewTitle {
            get {
                return ResourceManager.GetString("CommonErrorViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string SettingsAbout {
            get {
                return ResourceManager.GetString("SettingsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accounts.
        /// </summary>
        public static string SettingsAccounts {
            get {
                return ResourceManager.GetString("SettingsAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatic Responses.
        /// </summary>
        public static string SettingsAutoResponses {
            get {
                return ResourceManager.GetString("SettingsAutoResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        public static string SettingsMenuGeneral {
            get {
                return ResourceManager.GetString("SettingsMenuGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notifications.
        /// </summary>
        public static string SettingsNotifications {
            get {
                return ResourceManager.GetString("SettingsNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Personalization.
        /// </summary>
        public static string SettingsPersonalization {
            get {
                return ResourceManager.GetString("SettingsPersonalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Some changes will be applied after restart..
        /// </summary>
        public static string SettingsRestartMessage {
            get {
                return ResourceManager.GetString("SettingsRestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save changes.
        /// </summary>
        public static string SettingsSave {
            get {
                return ResourceManager.GetString("SettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save &amp; Restart.
        /// </summary>
        public static string SettingsSaveRestart {
            get {
                return ResourceManager.GetString("SettingsSaveRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Security.
        /// </summary>
        public static string SettingsSecurity {
            get {
                return ResourceManager.GetString("SettingsSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accent color.
        /// </summary>
        public static string SettingsUIAccentColor {
            get {
                return ResourceManager.GetString("SettingsUIAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Background color.
        /// </summary>
        public static string SettingsUIBackgroundColor {
            get {
                return ResourceManager.GetString("SettingsUIBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cache size:.
        /// </summary>
        public static string SettingsUICacheSize {
            get {
                return ResourceManager.GetString("SettingsUICacheSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear.
        /// </summary>
        public static string SettingsUIClearCache {
            get {
                return ResourceManager.GetString("SettingsUIClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blur background (reduces performance).
        /// </summary>
        public static string SettingsUIEnabledBlur {
            get {
                return ResourceManager.GetString("SettingsUIEnabledBlur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string SettingsUILanguage {
            get {
                return ResourceManager.GetString("SettingsUILanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show notification when track changes.
        /// </summary>
        public static string SettingsUINotifications {
            get {
                return ResourceManager.GetString("SettingsUINotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notifications.
        /// </summary>
        public static string SettingsUINotificationsTitle {
            get {
                return ResourceManager.GetString("SettingsUINotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show icon in the tray instead of taskbar.
        /// </summary>
        public static string SettingsUIShowTrayIcon {
            get {
                return ResourceManager.GetString("SettingsUIShowTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Taskbar.
        /// </summary>
        public static string SettingsUITaskBarTitle {
            get {
                return ResourceManager.GetString("SettingsUITaskBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check now.
        /// </summary>
        public static string SettingsUpdatesCheck {
            get {
                return ResourceManager.GetString("SettingsUpdatesCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatically check and install updates on start.
        /// </summary>
        public static string SettingsUpdatesCheckForUpdates {
            get {
                return ResourceManager.GetString("SettingsUpdatesCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test updates may contain new features and can be released more often but also can be unstable..
        /// </summary>
        public static string SettingsUpdatesDevUpdatesDescription {
            get {
                return ResourceManager.GetString("SettingsUpdatesDevUpdatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Install test updates.
        /// </summary>
        public static string SettingsUpdatesInstallDevUpdates {
            get {
                return ResourceManager.GetString("SettingsUpdatesInstallDevUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart.
        /// </summary>
        public static string SettingsUpdatesRestart {
            get {
                return ResourceManager.GetString("SettingsUpdatesRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mailer was updated. Restart to apply changes..
        /// </summary>
        public static string SettingsUpdatesUpdated {
            get {
                return ResourceManager.GetString("SettingsUpdatesUpdated", resourceCulture);
            }
        }
    }
}
