//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mailer.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mailer.Resources.Localization.MainResources", typeof(MainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IMAP address.
        /// </summary>
        public static string AccountImapAddr {
            get {
                return ResourceManager.GetString("AccountImapAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use SSL for IMAP.
        /// </summary>
        public static string AccountImapSsl {
            get {
                return ResourceManager.GetString("AccountImapSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string AccountLogin {
            get {
                return ResourceManager.GetString("AccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name in messages.
        /// </summary>
        public static string AccountMessagesName {
            get {
                return ResourceManager.GetString("AccountMessagesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string AccountPassword {
            get {
                return ResourceManager.GetString("AccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string AccountSave {
            get {
                return ResourceManager.GetString("AccountSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select an account or add new.
        /// </summary>
        public static string AccountSelect {
            get {
                return ResourceManager.GetString("AccountSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account setup.
        /// </summary>
        public static string AccountSetup {
            get {
                return ResourceManager.GetString("AccountSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMTP address.
        /// </summary>
        public static string AccountSmtpAddr {
            get {
                return ResourceManager.GetString("AccountSmtpAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use SSL for SMTP.
        /// </summary>
        public static string AccountSmtpSsl {
            get {
                return ResourceManager.GetString("AccountSmtpSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username.
        /// </summary>
        public static string AccountUsername {
            get {
                return ResourceManager.GetString("AccountUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new folder.
        /// </summary>
        public static string AddFolderHint {
            get {
                return ResourceManager.GetString("AddFolderHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на As Readed.
        /// </summary>
        public static string AsReaded {
            get {
                return ResourceManager.GetString("AsReaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на As Unreaded.
        /// </summary>
        public static string AsUnreaded {
            get {
                return ResourceManager.GetString("AsUnreaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We are sorry but something goes wrong. We will try to fix this as soon as possible..
        /// </summary>
        public static string CommonErrorViewContent {
            get {
                return ResourceManager.GetString("CommonErrorViewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart.
        /// </summary>
        public static string CommonErrorViewRestart {
            get {
                return ResourceManager.GetString("CommonErrorViewRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Oh... something happened :(.
        /// </summary>
        public static string CommonErrorViewTitle {
            get {
                return ResourceManager.GetString("CommonErrorViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New folder.
        /// </summary>
        public static string CreateFolder {
            get {
                return ResourceManager.GetString("CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folders.
        /// </summary>
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear.
        /// </summary>
        public static string FoldersClear {
            get {
                return ResourceManager.GetString("FoldersClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string FoldersDelete {
            get {
                return ResourceManager.GetString("FoldersDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading all the necessary information....
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string MessageClose {
            get {
                return ResourceManager.GetString("MessageClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string MessagesDelete {
            get {
                return ResourceManager.GetString("MessagesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mark.
        /// </summary>
        public static string MessagesMark {
            get {
                return ResourceManager.GetString("MessagesMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move.
        /// </summary>
        public static string MessagesMove {
            get {
                return ResourceManager.GetString("MessagesMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string NewFolderName {
            get {
                return ResourceManager.GetString("NewFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMTP Setup.
        /// </summary>
        public static string OmsSetup {
            get {
                return ResourceManager.GetString("OmsSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string SettingsAbout {
            get {
                return ResourceManager.GetString("SettingsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new.
        /// </summary>
        public static string SettingsAccountAdd {
            get {
                return ResourceManager.GetString("SettingsAccountAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string SettingsAccountDelete {
            get {
                return ResourceManager.GetString("SettingsAccountDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string SettingsAccountEdit {
            get {
                return ResourceManager.GetString("SettingsAccountEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accounts.
        /// </summary>
        public static string SettingsAccounts {
            get {
                return ResourceManager.GetString("SettingsAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select an account to edit or use.
        /// </summary>
        public static string SettingsAccountSelectAccount {
            get {
                return ResourceManager.GetString("SettingsAccountSelectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatic replies settings.
        /// </summary>
        public static string SettingsAutomaticReplies {
            get {
                return ResourceManager.GetString("SettingsAutomaticReplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatic Responses.
        /// </summary>
        public static string SettingsAutoResponses {
            get {
                return ResourceManager.GetString("SettingsAutoResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable automatic replies for this account.
        /// </summary>
        public static string SettingsEnableAutoReplies {
            get {
                return ResourceManager.GetString("SettingsEnableAutoReplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your message here.
        /// </summary>
        public static string SettingsEnterText {
            get {
                return ResourceManager.GetString("SettingsEnterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        public static string SettingsMenuGeneral {
            get {
                return ResourceManager.GetString("SettingsMenuGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notifications.
        /// </summary>
        public static string SettingsNotifications {
            get {
                return ResourceManager.GetString("SettingsNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Personalization.
        /// </summary>
        public static string SettingsPersonalization {
            get {
                return ResourceManager.GetString("SettingsPersonalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Some changes will be applied after restart..
        /// </summary>
        public static string SettingsRestartMessage {
            get {
                return ResourceManager.GetString("SettingsRestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save changes.
        /// </summary>
        public static string SettingsSave {
            get {
                return ResourceManager.GetString("SettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save &amp; Restart.
        /// </summary>
        public static string SettingsSaveRestart {
            get {
                return ResourceManager.GetString("SettingsSaveRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Security.
        /// </summary>
        public static string SettingsSecurity {
            get {
                return ResourceManager.GetString("SettingsSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password Reminder.
        /// </summary>
        public static string SettingsSecurityPasswordReminder {
            get {
                return ResourceManager.GetString("SettingsSecurityPasswordReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use a password to access the application.
        /// </summary>
        public static string SettingsSecurityUsePassword {
            get {
                return ResourceManager.GetString("SettingsSecurityUsePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accent color.
        /// </summary>
        public static string SettingsUIAccentColor {
            get {
                return ResourceManager.GetString("SettingsUIAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Background color.
        /// </summary>
        public static string SettingsUIBackgroundColor {
            get {
                return ResourceManager.GetString("SettingsUIBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cache size:.
        /// </summary>
        public static string SettingsUICacheSize {
            get {
                return ResourceManager.GetString("SettingsUICacheSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear.
        /// </summary>
        public static string SettingsUIClearCache {
            get {
                return ResourceManager.GetString("SettingsUIClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blur background (reduces performance).
        /// </summary>
        public static string SettingsUIEnabledBlur {
            get {
                return ResourceManager.GetString("SettingsUIEnabledBlur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string SettingsUILanguage {
            get {
                return ResourceManager.GetString("SettingsUILanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show notification when track changes.
        /// </summary>
        public static string SettingsUINotifications {
            get {
                return ResourceManager.GetString("SettingsUINotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notifications.
        /// </summary>
        public static string SettingsUINotificationsTitle {
            get {
                return ResourceManager.GetString("SettingsUINotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show icon in the tray instead of taskbar.
        /// </summary>
        public static string SettingsUIShowTrayIcon {
            get {
                return ResourceManager.GetString("SettingsUIShowTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Taskbar.
        /// </summary>
        public static string SettingsUITaskBarTitle {
            get {
                return ResourceManager.GetString("SettingsUITaskBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check now.
        /// </summary>
        public static string SettingsUpdatesCheck {
            get {
                return ResourceManager.GetString("SettingsUpdatesCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatically check and install updates on start.
        /// </summary>
        public static string SettingsUpdatesCheckForUpdates {
            get {
                return ResourceManager.GetString("SettingsUpdatesCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test updates may contain new features and can be released more often but also can be unstable..
        /// </summary>
        public static string SettingsUpdatesDevUpdatesDescription {
            get {
                return ResourceManager.GetString("SettingsUpdatesDevUpdatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Install test updates.
        /// </summary>
        public static string SettingsUpdatesInstallDevUpdates {
            get {
                return ResourceManager.GetString("SettingsUpdatesInstallDevUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart.
        /// </summary>
        public static string SettingsUpdatesRestart {
            get {
                return ResourceManager.GetString("SettingsUpdatesRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mailer was updated. Restart to apply changes..
        /// </summary>
        public static string SettingsUpdatesUpdated {
            get {
                return ResourceManager.GetString("SettingsUpdatesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show notifications about new messages.
        /// </summary>
        public static string ShowNotifications {
            get {
                return ResourceManager.GetString("ShowNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMTP address.
        /// </summary>
        public static string SmtpAddressTitle {
            get {
                return ResourceManager.GetString("SmtpAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string SmtpEmailTitle {
            get {
                return ResourceManager.GetString("SmtpEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMTP auth needed.
        /// </summary>
        public static string SmtpNeedAuth {
            get {
                return ResourceManager.GetString("SmtpNeedAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string SmtpPasswordTitle {
            get {
                return ResourceManager.GetString("SmtpPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMTP Setup.
        /// </summary>
        public static string SmtpSetupTitle {
            get {
                return ResourceManager.GetString("SmtpSetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use SSL for SMTP.
        /// </summary>
        public static string SmtpUseSslTitle {
            get {
                return ResourceManager.GetString("SmtpUseSslTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use image as custom background.
        /// </summary>
        public static string UseImageAsBg {
            get {
                return ResourceManager.GetString("UseImageAsBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please, wait....
        /// </summary>
        public static string WaitMessage {
            get {
                return ResourceManager.GetString("WaitMessage", resourceCulture);
            }
        }
    }
}
